{
    'name': 'ICE AGE',
    'author': 'Usman Ghias',
    'summary': 'Deep Learning Based Framework for Monitoring of Debris Glaciers',
    'description': """Debris Glaciers Module""",
    'category': 'web',
    'website': 'https://www.codcrafters.org/',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'views/form_view.xml',
        'views/templates.xml',
    ],
    # 'qweb': [],
    'demo': [],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}